# Generated by Django 5.0.6 on 2024-06-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_candidate_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
