# Generated by Django 5.0.6 on 2024-06-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_application_candidate_remove_application_job_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
