# Generated by Django 5.0.6 on 2024-06-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name_plural': 'Work Experience'},
        ),
    ]
