# Generated by Django 5.0.6 on 2024-07-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
