# Generated by Django 5.0.6 on 2024-07-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'User Profile'},
        ),
    ]
