# Generated by Django 5.0.6 on 2024-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_applications_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
