# Generated by Django 5.0.6 on 2024-06-18 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
