# Generated by Django 5.0.6 on 2024-07-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_profile_facebook_profile_instagram_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
