# Generated by Django 5.0.6 on 2024-06-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_jobs_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='adder',
        ),
    ]
